version: '3.3'
services:
  redis:
    image: redis:5.0.1
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=paascloud@redis
    volumes:
      - redis-data:/bitnami/redis/data

volumes:
  redis-data:
